services:
  api:
    build: ./api
    container_name: doc_ingest_api
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - ollama

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

volumes:
  qdrant_data:
  ollama:
